// Command _gen generates lz4block's assembly decoders.
//
// Run it through go generate in internal/lz4block. Each decoder is written
// as blocks of Go assembly, with the repeated copy and store loops built by
// helpers, and formatted with asmfmt.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/klauspost/asmfmt"
)

func main() {
	arch := flag.String("arch", "arm64", "architecture to generate")
	out := flag.String("out", "", "output file (default stdout)")
	flag.Parse()

	var a asm
	switch *arch {
	case "amd64":
		decodeAMD64(&a)
	case "arm64":
		decodeARM64(&a)
	default:
		log.Fatalf("unsupported -arch %q", *arch)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by \"go run -C _gen . -arch %s\"; DO NOT EDIT.\n\n", *arch)
	b.Write(a.buf.Bytes())
	src, err := asmfmt.Format(&b)
	if err != nil {
		log.Fatal(err)
	}
	if *out == "" {
		os.Stdout.Write(src)
		return
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// asm accumulates assembly source. asmfmt aligns it afterwards, so blocks
// need not be aligned by hand.
type asm struct{ buf bytes.Buffer }

// I appends lines of assembly. A leading newline is dropped so a raw
// string can start on the line after its opening quote.
func (a *asm) I(s string) {
	s = strings.TrimPrefix(s, "\n")
	a.buf.WriteString(s)
	if !strings.HasSuffix(s, "\n") {
		a.buf.WriteByte('\n')
	}
}

// F appends lines of assembly formatted by fmt.Sprintf.
func (a *asm) F(format string, args ...any) { a.I(fmt.Sprintf(format, args...)) }

// macro appends a #define of name whose body is the given lines.
func (a *asm) macro(name, body string) {
	var lines []string
	for _, l := range strings.Split(body, "\n") {
		if l != "" {
			lines = append(lines, l)
		}
	}
	a.F("#define %s \\", name)
	for i, l := range lines {
		if i < len(lines)-1 {
			l += " \\"
		}
		a.I(l)
	}
}
